task:
  name: Test (x86)
  container:
    dockerfile: .ci/Dockerfile.x86
    cpu: 4
    memory: 10G
    kvm: true
  pub_cache:
    folder: ~/.pub-cache
  start_emulator:
    - EMU_PARAMS="
      -avd test
      -verbose
      -no-window
      -no-audio
      "
    - ${ANDROID_HOME}/emulator/emulator-headless ${EMU_PARAMS} &
    # wait for emulator to finish startup
    - ./script/android-wait-for-emulator.sh
    # unlock screen
    - adb shell input keyevent 82 &

    - flutter doctor -v
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter drive test_driver/main.dart